import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 配置路径
const SCRIPTURES_DIR = path.join(__dirname, '../scriptures');
const OUTPUT_FILE = path.join(__dirname, '../src/data/scriptures.ts');

// 确保目录存在
if (!fs.existsSync(SCRIPTURES_DIR)) {
    console.error(`❌ 错误：找不到经文目录: ${SCRIPTURES_DIR}`);
    process.exit(1);
}

// 读取所有 .txt 文件
const files = fs.readdirSync(SCRIPTURES_DIR).filter(file => file.endsWith('.txt'));

if (files.length === 0) {
    console.warn(`⚠️ 警告：scriptures 目录中没有找到 .txt 文件。`);
    // 不退出，允许生成空列表（或保留默认）
}

console.log(`📚 发现 ${files.length} 个经文文件，开始处理...`);

const scriptures = files.map(file => {
    const filePath = path.join(SCRIPTURES_DIR, file);
    const rawContent = fs.readFileSync(filePath, 'utf-8');

    // 解析文件内容
    // 约定：
    // 第一行：标题
    // 第二行：作者/译者（可选，如果不想写作者，留空行）
    // 第三行及以后：正文

    const lines = rawContent.split(/\r?\n/);
    const title = lines[0] ? lines[0].trim() : '无标题';
    const author = lines[1] ? lines[1].trim() : '';

    // 从第三行开始是正文，重新组合并去除首尾空白
    const content = lines.slice(2).join('\n').trim();

    // ID 使用文件名（去掉.txt）
    const id = path.basename(file, '.txt');

    // 计算字数
    const size = content.replace(/\s/g, '').length + '字';

    return {
        id,
        title,
        author,
        description: content.substring(0, 60).replace(/\n/g, ' ') + '...', // 自动生成简介
        size,
        audioUrl: '/assets/audio/heart-sutra.mp3', // 默认音频，后续可扩展
        content
    };
});

// 生成 TypeScript 代码
const tsContent = `// ⚠️ 此文件由 scripts/import_scriptures.js 自动生成，请勿手动修改
// ⚠️ Generated by scripts/import_scriptures.js - DO NOT EDIT MANUALLY

export interface Scripture {
    id: string;
    title: string;
    author?: string;
    description: string;
    size?: string;
    coverImage?: string;
    audioUrl: string;
    bgmUrl?: string;
    content: string;
    pages?: string[];
}

export const scriptures: Scripture[] = ${JSON.stringify(scriptures, null, 4)};
`;

// 写入文件
fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf-8');

console.log(`✅ 成功生成 ${scriptures.length} 部经文到 src/data/scriptures.ts`);
